### ISSUE TITLE
Idea:  Automatic identification of Test/Normal Mode in Xiaomi Aqara Motion Sensors

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#111]
Yesterday I was exploring something which I wasn't able to get too far on before I had to leave the house. 

There is a cluster which _**as far as I can tell**_ , after the sensor has been paired, is _always and only_ sent when the reset button is pressed - cluster 0000, attrib 0005 which gives the model (see bolded below). As we've identified - initial pairing and resetting sends the sensor into test mode - during which time it responds to motion every 5-6 seconds instead of the default 60.

I've only tested after pairing - but I have a hunch it would also be shown at initial pairing (or there would be another way to identify pairing). 

This is already parsed out by the existing DTH. 

Thinking it could be a tile that automatically indicates Test Mode this cluster is reported - sets a 2 hour timer, then resets to normal.

Thoughts?   Anyone else have other experiences w/ this cluster? 

Alec

**d5b99a48-1ec2-4624-b142-435eac76f60a 2:09:20 PM: debug Bathroom Door Motion Sensor III reported: cluster: 0000, attrId: 0005, model:lumi.sensor_motion.aq2**
d5b99a48-1ec2-4624-b142-435eac76f60a 2:09:20 PM: debug Bathroom Door Motion Sensor III parsing: read attr - raw: 9CD401000034050042166C756D692E73656E736F725F6D6F74696F6E2E617132, dni: 9CD4, endpoint: 01, cluster: 0000, size: 34, attrId: 0005, encoding: 42, value: 6C756D692E73656E736F725F6D6F74696F6E2E617132

**Comment by veeceeoh** [comment]
While working on my new Pull Request, I considered the idea of automatically putting the DTH into Testing Mode. But I realized a few things:
 
1. There is no way that I'm aware of for the DTH to "see" that the sensor hardware has finished Test Mode.
2. It's pretty much impossible to guarantee that the DTH will correctly set up Testing Mode on pairing if the user pairs via the "catchall" method.
3. If a user unintentionally puts an already installed sensor into hardware test mode, then automatically putting the DTH into Testing Mode would negatively impact any automations that user has set up for the sensor. The reason I started in on reworking the code was exactly this - a user changed to the bspranger/Xiaomi  DTH and was apparently not aware of the hardware Test Mode or at least did not expect it to negatively affect his automations. This was a reasonable expectation because he assumed the 60 second motion reset setting default would work correctly.

So I shy away from the idea an automatic DTH "Testing Mode" being thrust upon the user. I think it would be better to alert the user to the _probability_ that the sensor is in Test Mode when it is first paired or the reset button is short-pressed. But then it would be the users choice to put the DTH into Testing Mode or not.

As for the cluster 0000 attribute 0005 method to determine whether it corresponds to hardware test mode via short-press of the reset button, a bunch of testing would need to be done, and it will take time, since it can only be checked/verified when the sensor is in normal hardware more.

Also, I thought about adding a tile to indicate the sensor is in the DTH "Testing Mode", but then I would have to guess that most people only need to use Test Mode to determine the best location for installation, so it's not really a normal function of operation for the majority of usage. But yes, a tile could be added which could either just be an indicator of hardware Test Mode or DTH Testing Mode is active, or also act as the toggle switch to turn DTH Testing Mode on or off.

**Comment by alecm** [comment]
I agree -  all I'm suggesting is an indicator showing that the sensor is probably in testing mode (e.g., just paired plus two hours or button pressed plus 2 hours).   I would not want it to have any effect when pressed.  I'm fine to keep on testing the validity of the cluster 0000, attrib 0005 as an identifier - and I'll keep logging running just in case it sends something when 'time's up' (though I agree it's unlikely).  Although testing mode is 'rare'  - I think there is value in identifying it because of its significant temporary effect on sensor behavior.

**Comment by veeceeoh** [comment]
Ah, okay, sounds good.

**Comment by alecm** [comment]
@veeceeoh -  closing this - it turns that if sensor is already paired,   cluster 0000 attribute 0005 notification happens only if you press reset while _already_ in testing mode - does not happen on initial push that puts it into the test mode.  Don't think this is worth pursuing any further.
