### ISSUE TITLE
Aqara devices disconnecting after a few minutes/hours

### ISSUE THREAD

**Issue by babbahotep** [bspranger/Xiaomi#123]
Hi,

I am about to give up on these. Have Aqara square switch, small button, temp, vibration, motion sensors.
They pair and then a few hours later they are gone and don't show up again unless reset. Reading the forum thread I dont seem to be the only one. 

Any chance of fixing that ?

Im using Hub v2, US customer Rev E fw: 000.022.00014

thanks

**Comment by oldirtyewok** [comment]
I'm just curious, which smartthings hub are you using?  Ive had the exact same problem with a Samsung home connect. It would connect but wouldnt stay connected for more than an hour.
Likewise I've read people with the Nvidia sheild smartthings dongle also exhibits the same problem.

I fought with it for days and weeks when i had my samsung connect home.
I gave up and switched to a Samsung Smartthings Hub V2... Never had a proble with connections since.

**Comment by veeceeoh** [comment]
@babbahotep - There's nothing about the device handlers that can help with that issue.

When they drop their connection it has to do with the ZigBee "end device aging" timeout of the hub, or a Zigbee repeater - if the Xiaomi device is connected to one. 

If that end device aging timeout is _shorter_ than the Xiaomi device's regular check-in interval (either every 50 or 60 minutes depending on whether it's Aqara or not) then the hub/repeater kicks it off its list of connected devices. 

The issue occurs when the Xiaomi device tries to check-in after the end device aging timeout has passed by. The hub/repeater asks the device to re-join, and for some reason Xiaomi devices never rejoin (while normally a Zigbee device _would_ rejoin, and you'd never know it was kicked off.)

So if you've got a V2 SmartThings hub and definitely have no Zigbee repeater devices connected, then perhaps SmartThings changed something about the end device aging timeout. Otherwise, if you _do_ have one or more Zigbee repeater devices, then they are very likely the reason why you've seen a change in your Xiaomi devices losing their connection.

The only Zigbee repeater device that seems to work consistently with Xiaomi devices is an XBee module.

**Comment by babbahotep** [comment]
My aqara devices are all 6 feet from the hub along with a few samsung oem outlets.

**Comment by veeceeoh** [comment]
It's very likely the Samsung Smart Outlets. They are Zigbee-based, and do act as repeaters.

If possible, try _unplugging_ all of the Samsung Smart Outlets, re-pair one or more of your Aqara devices, and see if it/they stay connected more than a couple of hours.

**Comment by babbahotep** [comment]
have done it, same result. 
 Samsung wins, going to buy their stuff now...
anyone want 8 mixed xiaomi aqara sensors?

**Comment by frozenfame** [comment]
I'll take them! what do you have?
