### ISSUE TITLE
Xiaomi Aqara Vibration Sensor - tiltAngle inconsistent

### ISSUE THREAD

**Issue by jdtoth** [bspranger/Xiaomi#130]
I have this on my overhead garage door. The tiltAngle in the open or closed position isn't consistent. It will always be within 1-2 degrees. For example, at closed it will report it as either 99 or 98, and at the open position it reports as 101 or 102. I suspect there is some logic in the rounding function that can be adjusted?

**Comment by veeceeoh** [comment]
The tiltAngle events are just the raw data from the sensor passed on, and there is no rounding function. I have no plans to incorporate rounding for tiltAngle because it is a custom attribute not directly supported in SmartThings. It would be better to build that kind of support in a custom SmartApp or implement it in a WebCoRE priston.

Really if you are just wanting open / close events for a garage door based on angle, use the contact open/close feature of the device handler. You will need to manually set up the open close positions by pressing the “set open” / “set close” buttons for the device in the SmartThings classic mobile app. That function uses the 3-axis accelerometer data which is more reliable and does use a kind of rounding function so that the position does not have to be exact. On this, I may open up the rounding/margin of error value to be user adjustable. But first I’d like to hear how well the default setup is working for people.

**Comment by jdtoth** [comment]
Thanks for the response. I was using the set open/close function but it doesn't work consistently either. I am assuming because the 3-axis accelerometer does not report consistently as well. I think your suggestion to open up the error margin will fix the issue for me. Perhaps with a low/medium/high like the accel sensitivity has, or just make that an overall sensitivity for both things?

**Comment by jdtoth** [comment]
Please disregard, I see in your code you're already using a margin of error of 10. Looking through the logs, none of the axis fluctuations come close to this margin. I can see the logs sometimes do not record axis values (I see axis values for an open door twice in a row and many hours apart, which means it missed the close). When this happened, I see an 'unknown' contact value at the same time. I'm going to monitor to see if this is related.

**Comment by veeceeoh** [comment]
If you're seeing missed axis value reports when the door is closed, that is due to the behavior of the sensor itself. From my experience so far, this sensor's behavior is quirky, and for some of its functions (like the activity level value reporting), I am not seen complete consistency to how often / when it sends reports / messages. Also, it completely fails to be useful in some situations where it should in theory work well. For example, it did not send any vibration/shock reports at all when I tested it on my clothes washing machine.

So unfortunately, it may just be that case that determining an overhead garage door open / close position is an inappropriate use for this sensor. Is it not possible to use a magnetic contact sensor with your garage door?

**Comment by jdtoth** [comment]
I think you might be right. This sensor consistently skips reporting a
tiltAngle or Axis 1-2x over a 24 hour period.

A magnetic contact sensor is tough with a garage door but I'll reexamine
the placement.
