### ISSUE TITLE
Aqara Wall Switch QBKG04LM (one button, NO neutral)

### ISSUE THREAD

**Issue by poki123** [bspranger/Xiaomi#133]
Hello, I made some dirty, but functional code for the Aqara Wall Switch QBKG04LM.

Is it possible to check it please? And integrate here?
Im not programmer.
As I know, fingerprint is not ok, but everything is working.
Thank you,
J.
[Aqara.txt](https://github.com/bspranger/Xiaomi/files/2705358/Aqara.txt)

**Comment by veeceeoh** [comment]
Neither @bspranger nor I have any way to test your code because we do not own the Aqara Wall Switch model QBKG04LM and that model wouldn't work because we're both in the USA.

As I understand it, there is already a device driver for the Aqara wired Wall Switches available on the SmartThings Community Forums [here](https://community.smartthings.com/t/device-handler-for-aqara-wired-wall-switch/101062).

Best of luck!

**Comment by drsheshank** [comment]
> Hello, I made some dirty, but functional code for the Aqara Wall Switch QBKG04LM.
> 
> Is it possible to check it please? And integrate here?
> Im not programmer.
> As I know, fingerprint is not ok, but everything is working.
> Thank you,
> J.
> [Aqara.txt](https://github.com/bspranger/Xiaomi/files/2705358/Aqara.txt)

Do you need the aqara hub for this to work? I have the STv3 hub only!

Thanks
