### ISSUE TITLE
Temperature Humidity Sensor doesn't have pressure in REST API response 

### ISSUE THREAD

**Issue by moikot** [bspranger/Xiaomi#140]
I'm trying to use SmartThings REST API to access Xiaomi Aqara Temperature Humidity Sensor.
But the response does not include pressure.
```json
{
    "components": {
        "main": {
            "relativeHumidityMeasurement": {
                "humidity": {
                    "value": 42,
                    "unit": "%"
                }
            },
            "healthCheck": {
                "checkInterval": {
                    "value": 7320,
                    "unit": "s",
                    "data": {
                        "protocol": "zigbee",
                        "hubHardwareId": "000E"
                    }
                },
                "healthStatus": {
                    "value": null,
                    "data": {}
                },
                "DeviceWatch-DeviceStatus": {
                    "value": null,
                    "data": {}
                }
            },
            "temperatureMeasurement": {
                "temperature": {
                    "value": 19.9,
                    "unit": "C"
                }
            },
            "sensor": {},
            "battery": {
                "battery": {
                    "value": 83,
                    "unit": "%"
                }
            }
        }
    }
}
```
Would it be possible to add atmospheric pressure to the response?

**Comment by veeceeoh** [comment]
I'm sorry to say that SmartThings does not officially support an **air pressure capability** when developing device handlers.

If you take a look at SmartThings capabilities reference page in the [Classic Developer's Documentation](https://docs.smartthings.com/en/latest/capabilities-reference.html) and the [new Developer's Documentation](https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html), you will see that no pressure capability is listed.

So, in order to generate air pressure value events, the Aqara Temperature / Humidity sensor device handler makes use of a **custom attribute**.

I do not use SmartThings' REST API personally, so I am not sure how to get custom attribute event values to appear in the response. I suggest searching the SmartThings Community Forums for more information.

I did find [this thread](https://community.smartthings.com/t/accessing-pressure-data-from-xiaomi-aqara/152881) where someone asked the same question.

**Comment by moikot** [comment]
Thank you a lot for the explanation, I'll follow the links!
