### ISSUE TITLE
Idea: Alexa Smartthings skill temperature reporting

### ISSUE THREAD

**Issue by tylerdurden94** [bspranger/Xiaomi#77]
Currently, I can ask Alexa to tell me the current temperature reading on my thermostat device via the Smartthings Alexa skill.  But it won't work on the temperature sensor.  I'm wondering if this might be possible if the temp sensor DTH emulates the characterstics of a thermostat so that the ST Alexa skill will interact with it.

**Comment by tmleafs** [comment]
You need to install ask alexa or wait till echosistant v5 ti be released has a much easier setup (im on the beta team)

**Comment by veeceeoh** [comment]
I see [the thread on the SmartThings Community forums](https://community.smartthings.com/t/temperature-sensor-that-works-with-alexa/117345?u=veeceeoh) where you've floated this idea.

Just as discussed there, the ST Alexa skill supports asking the temperature of thermostat devices. It's a bad idea to code the device handler of a temperature sensor to "pretend" to be a thermostat, because then all SmartApps would see the sensors as having full thermostat capabilities, leading to confusion by users on how to properly integrate them into their SmartThings setup. 

Also, as mentioned in the thread, the Ask Alexa or the new upcoming version of Echosistant would be the best way to go.

However, by all means, end users are welcome to custom-modify device handler code to suit their needs. I use Alexa devices at home, and when my Xiaomi Aqara Temp / Humidity sensor arrives tomorrow, I can try experimenting with the device handler code to see whether adding the tag for thermostat capability works or breaks things, and then pass on what code modification would get it working (if any).

**Comment by alecm** [comment]
Just as a note - Alexa will also give me temperature from Ecobee sensors - instead of just the Ecobee - that's through its Ecobee integration of course - but still, maybe one doesn't need a full thermostat definition.  Just a thought.

**Comment by veeceeoh** [comment]
So is it recognizing your Ecobee sensors through the Ecobee Alexa Skill or the SmartThings skill?

**Comment by tmleafs** [comment]
alexa is very limited thats why 'ask alexa' exists with smart home devices only the following commands can be used https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201749260

**Comment by tylerdurden94** [comment]
Alexa can read back my Sensi Thermostat temp via the ST skill.   I  disabled the Sensi skill because it couldn't.




I noticed someone had created a virtual thermostat DTH (not just smartapp) on the ST community that let's you designate a sensor.  I haven't had time to see if that could bridge the gap.




On Mon, Feb 5, 2018 at 3:02 PM -0600, "Keith G" <notifications@github.com> wrote:












So is it recognizing your Ecobee sensors through the Ecobee Alexa Skill or the SmartThings skill?

**Comment by bspranger** [comment]
should this request be closed?

**Comment by alecm** [comment]
Through the Ecobee skill... (to answer @veeceeoh ).

**Comment by tmleafs** [comment]
I vote close

**Comment by foz333** [comment]
close... not a dt feature and can be acomplished with "ask alexa"

**Comment by tylerdurden94** [comment]
Doesn't ask alexa require additional BT speakers?  Or is it fully functional with only the echo device? Other DTHs have done something similar such as enabling a garage door DTH to communicate as a switch for Alexa compatibility.  




On Wed, Feb 14, 2018 at 2:42 PM -0600, "foz333" <notifications@github.com> wrote:












close... not a dt feature and can be acomplished with "ask alexa"
