### ISSUE TITLE
IDEA:  Multiclick on both buttons

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#91]
Documentation from Zigate implies that both buttons have multiclick - with value of 1 to 4.  Maybe we should look at parsing that.

(PS - thanks @veeceeoh for pointing me at these pages - I'd only found a more generic one from this guy before) 

Alec 

http://zigate.fr/xiaomi-bouton-switch-cluster/

ZiGate <- 01 81 02 00 0E F3 0B C0 E1 01 00 06 80 00 00 20 00 01 02 F0 03

Type: 0x8102 (Attribute Report)
SQN: 0x0B
Src Addr: 0xC0E1
Src Ep: 0x01
Cluster ID: 0x0006 (General: On/Off)
Attribute ID: 0x8000
Attribute Size: 0x0001
Attribute Type: 0x20 (UINT8)
Attribute Data: 0x02
Status: 0x00

**0x02 = nombre de clics (max 4)**

http://zigate.fr/xiaomi-bouton-switch-aqara-clusters/

Multi clics
ZiGate <- 01 81 02 00 0E E5 06 82 97 01 00 06 80 00 00 20 00 01 03 DE 03

Type: 0x8102 (Attribute Report)
SQN: 0x06
Src Addr: 0x8297
Src Ep: 0x01
Cluster ID: 0x0006 (General: On/Off)
Attribute ID: 0x8000
Attribute Size: 0x0001
Attribute Type: 0x20 (UINT8)
Attribute Data: 0x03
Status: 0x00

**0x03 = nombre de clics (max 4)**

**Comment by veeceeoh** [comment]
I'm afraid this can't be done.

Unfortunately the SmartThings ZigBee API abstraction layer strips all data that would allow the device handler to see anything besides a single button press.

I have the [Xiaomi WXKG02LM Aqara two-panel wall-mount switch](https://www.gearbest.com/alarm-systems/pp_610095.html), and because of SmartThings stupid API, all I see is the same button press for either side. The switch actually send different data if you press the left, right, or both at the same time. It is very frustrating not to have access to the full messages sent by the device (and other Xiaomi devices, for that matter)

This is why I have bought the new Hubitat hub.

**Comment by alecm** [comment]
Dang - that's annoying!!!!

I'm tempted by the Hubitat -

**Comment by veeceeoh** [comment]
I don't know how long they will have the $50 off deal, but I can't say whether the Xiaomi devices will work properly with it until I've gotten mine.

They only allow hub owners full Community Forum access, so technical information and support is a bit sparse as a non-user.

All I have is [an invitation](https://community.hubitat.com/t/compatible-devices-list/113/68) from one of the founders, Bruce Ravenel (creator of the ST SmartApp Rules Machine) to buy a hub and work with them to solve the problem of accessing all the ZigBee data necessary to gain full access to all features of Xiaomi devices.

**Comment by alecm** [comment]
ah well - I'll close this for now and ponder the hubitat - I'm on thin ice already w/ the husband on how many devices I've been bringing in .....
